// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpN23bUqMrjRXiuCO47ehnR1u08X-X3sE',
    appId: '1:530577120175:web:aafb0290cac91811142d5a',
    messagingSenderId: '530577120175',
    projectId: 'oweme-64f77',
    authDomain: 'oweme-64f77.firebaseapp.com',
    storageBucket: 'oweme-64f77.firebasestorage.app',
    measurementId: 'G-LTGPNVMYPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW2dYPZ0O6iQ5RJ1U6f-U5n1rpRpxpFlI',
    appId: '1:530577120175:android:5308cdbd4575e917142d5a',
    messagingSenderId: '530577120175',
    projectId: 'oweme-64f77',
    storageBucket: 'oweme-64f77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpcDl5aaVgUGTV1K3v1jg5sOzSe9icnYU',
    appId: '1:530577120175:ios:a25acafea9448a10142d5a',
    messagingSenderId: '530577120175',
    projectId: 'oweme-64f77',
    storageBucket: 'oweme-64f77.firebasestorage.app',
    iosBundleId: 'com.example.oweme',
  );
}
